# Generated by Django 4.0.4 on 2022-05-16 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DailyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('preview', models.ImageField(blank=True, upload_to='preview-images/%Y/%m/%d/', verbose_name='Image Preview')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=400, verbose_name='Author Name')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('date', models.DateTimeField(blank=True, verbose_name='Date')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='*')),
                ('image', models.ImageField(blank=True, upload_to='Tag-images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Story Item Title')),
                ('type', models.CharField(choices=[('video', 'video'), ('photo', 'photo')], default='video', max_length=100)),
                ('file', models.FileField(blank=True, upload_to='story-files/%Y/%m/%d/', verbose_name='File')),
                ('date', models.DateTimeField(blank=True, verbose_name='Date Time')),
                ('story', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='storyitems', to='main.dailystory')),
            ],
            options={
                'verbose_name': 'StoryItems',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='Post-previews/%Y/%m/%d/', verbose_name='File')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postimages', to='main.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main.tag'),
        ),
    ]
