# Generated by Django 4.0.4 on 2022-05-11 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='*')),
                ('preview', models.ImageField(blank=True, upload_to='preview-images/% Y/% m/% d/', verbose_name='Image Preview')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Story Item Title')),
                ('file', models.FileField(blank=True, upload_to='story-files/% Y/% m/% d/', verbose_name='File')),
                ('date', models.DateTimeField(blank=True, verbose_name='Date Time')),
                ('story', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.dailystory')),
            ],
            options={
                'verbose_name': 'StoryItems',
            },
        ),
    ]
