# Generated by Django 4.0.4 on 2022-05-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystory',
            name='preview',
            field=models.ImageField(blank=True, upload_to='preview-images/%Y/%m/%d/', verbose_name='Image Preview'),
        ),
    ]
