# Generated by Django 4.0.4 on 2022-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dailystory_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyitem',
            name='file',
            field=models.FileField(blank=True, upload_to='story-files/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
