# Generated by Django 4.0.4 on 2022-05-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_slug_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_uz',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='preview_en',
            field=models.ImageField(blank=True, null=True, upload_to='preview-images/%Y/%m/%d/', verbose_name='Image Preview'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='preview_ru',
            field=models.ImageField(blank=True, null=True, upload_to='preview-images/%Y/%m/%d/', verbose_name='Image Preview'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='preview_uz',
            field=models.ImageField(blank=True, null=True, upload_to='preview-images/%Y/%m/%d/', verbose_name='Image Preview'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dailystory',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ru',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='author_uz',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Author Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='Post-previews/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='Post-previews/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='file_uz',
            field=models.FileField(blank=True, null=True, upload_to='Post-previews/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='story-files/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='story-files/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='file_uz',
            field=models.FileField(blank=True, null=True, upload_to='story-files/%Y/%m/%d/', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Story Item Title'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Story Item Title'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Story Item Title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='Tag-images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='Tag-images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='Tag-images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='*'),
        ),
    ]
