# Generated by Django 4.0.4 on 2022-05-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_storyitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyitem',
            name='story',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='storyitems', to='main.dailystory'),
        ),
    ]
