# Generated by Django 4.0.4 on 2022-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_storyitem_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitem',
            name='type',
            field=models.CharField(choices=[('Video', 'Video'), ('Video', 'Photo')], default='Video', max_length=100),
        ),
    ]
