# Generated by Django 4.0.4 on 2022-05-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_storyitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyitem',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('photo', 'photo')], default='video', max_length=100),
        ),
    ]
